language: csharp
mono: none
dotnet: SDK 3.0.100-preview-009812
script:
  - dotnet restore ./Source/
  - dotnet build ./Source/
  - dotnet test --no-build ./Source/UnitTests/
  - dotnet build -c Release --verbosity=minimal Source/Benchmarks
  - dotnet run -c Release -p Source/Benchmarks