version: 2.0.0.{build}
configuration: Debug
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alpha1'
  package_version: '{version}-alpha1'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alpha1'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore Source\ManagedIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build:
  project: Source\ManagedIrbis.sln
  publish_nuget: false
  parallel: true
  verbosity: minimal

after_build:
- cmd: compile.cmd

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=Source/Tests/UnitTests/results.trx /p:DebugType=full Source/Tests/UnitTests/UnitTests.csproj" -filter:"+[AM.Core]AM.* +[ManagedIrbis]* -[*]ManagedIrbis.Biblio.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:"%TEMP%\coverage.xml" -oldStyle
- codecov -f "%TEMP%\coverage.xml" -t b086eb50-83b2-419f-a1e2-47cc7750b482

artifacts:
  - path: Binaries
    name: ManagedIrbis2
  - path: 'Binaries\DebugCore\**\*.nupkg'
    name: Nuget
