version: 2.0.0.{build}
configuration: Debug
image: Visual Studio 2019 Preview
init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alpha1'
  package_version: '{version}-alpha1'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alpha1'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: appveyor DownloadFile -FileName dotnet-sdk.exe https://download.visualstudio.microsoft.com/download/pr/a46fa009-033b-430d-89a8-c9a107f73d87/d25f962e8212aafb3b0c426eb8cb4dc6/dotnet-sdk-3.0.100-preview8-013656-win-x64.exe
- cmd: dotnet-sdk.exe
- cmd: dotnet --info
- cmd: dotnet restore Source/ManagedIrbis.30.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build_script:
- dotnet msbuild "C:\projects\managedirbis2\Source\ManagedIrbis.30.sln" /m /verbosity:minimal

after_build:
- cmd: compile.cmd

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --no-build --logger:trx;LogFileName=Source/UnitTests/results.trx /p:DebugType=full Source/UnitTests/UnitTests.csproj" -filter:"+[AM.Core]AM.* -[*]AM.Core.Properties.* +[ManagedIrbis]* -[*]ManagedIrbis.Biblio.* -[*]ManagedIrbis.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:"%TEMP%\coverage.xml" -oldStyle
- codecov -f "%TEMP%\coverage.xml" -t b086eb50-83b2-419f-a1e2-47cc7750b482
- dotnet.exe build -c Release --verbosity=minimal Source\Benchmarks
- dotnet.exe run -c Release -p Source\Benchmarks

artifacts:
  - path: Binaries
    name: ManagedIrbis2
  - path: 'Binaries\DebugCore\**\*.nupkg'
    name: Nuget
