version: 2.0.0.{build}
configuration: Debug
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alpha1'
  package_version: '{version}-alpha1'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alpha1'

nuget:
  account_feed: false
  project_feed: false

before_build:
- ps:  Utils\dotnet-install.ps1 -Version 3.0.100-preview-009812
- cmd: dotnet --info
- cmd: dotnet restore Source\ManagedIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build_script:
- dotnet msbuild "C:\projects\managedirbis2\Source\ManagedIrbis.sln" /m /verbosity:minimal

after_build:
- cmd: compile.cmd

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Users/appveyor/AppData/Local/Microsoft/dotnet/dotnet.exe" -targetargs:"test --no-build --logger:trx;LogFileName=Source/UnitTests/results.trx /p:DebugType=full Source/UnitTests/UnitTests.csproj" -filter:"+[AM.Core]AM.* -[*]AM.Core.Properties.* +[ManagedIrbis]* -[*]ManagedIrbis.Biblio.* -[*]ManagedIrbis.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:"%TEMP%\coverage.xml" -oldStyle
- codecov -f "%TEMP%\coverage.xml" -t b086eb50-83b2-419f-a1e2-47cc7750b482
- C:/Users/appveyor/AppData/Local/Microsoft/dotnet/dotnet.exe build -c Release --verbosity=minimal Source\Benchmarks
- C:/Users/appveyor/AppData/Local/Microsoft/dotnet/dotnet.exe run -c Release -p Source\Benchmarks

artifacts:
  - path: Binaries
    name: ManagedIrbis2
  - path: 'Binaries\DebugCore\**\*.nupkg'
    name: Nuget
