# .NET Core
# Build and test .NET Core projects.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .net core 3.0'
  inputs:
    version: '3.0.100-preview8-013656'
- script: dotnet build --configuration $(buildConfiguration) Source/ManagedIrbis.30.sln
  displayName: 'dotnet build'
